FROM python:3.11-slim
WORKDIR /app

# Need libpq-dev to connect to PostgreSQL
RUN apt-get update && apt-get install -y --no-install-recommends \
    libpq-dev \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Create static folder for uploads
RUN mkdir -p static/gallery

EXPOSE 8000

# Run migrations THEN start server
CMD ["sh", "-c", "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"]
