"""add member_name and member_email to subscriptions

Revision ID: 6d14452b6618
Revises: f96e51a03f20
Create Date: 2026-05-25 14:51:22.450143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d14452b6618'
down_revision: Union[str, Sequence[str], None] = 'f96e51a03f20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('member_name', sa.String(), nullable=True))
    op.add_column('subscriptions', sa.Column('member_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'member_email')
    op.drop_column('subscriptions', 'member_name')
    # ### end Alembic commands ###
