"""add streak columns to members

Revision ID: f96e51a03f20
Revises: 9afc16d7f216
Create Date: 2026-05-16 09:52:22.406586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f96e51a03f20'
down_revision: Union[str, Sequence[str], None] = '9afc16d7f216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('current_streak', sa.Integer(), server_default='0', nullable=False))
    op.add_column('members', sa.Column('longest_streak', sa.Integer(), server_default='0', nullable=False))
    op.add_column('members', sa.Column('last_checkin_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'last_checkin_date')
    op.drop_column('members', 'longest_streak')
    op.drop_column('members', 'current_streak')
    # ### end Alembic commands ###
